name: Lint and Build Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.0
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint "src/**/*.{ts,html}" --config eslint.config.mjs

  build:
    name: Build application
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx nx build website --configuration=production
